server:
  port: 8091

spring:
  application:
    name: IPL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ballbyballdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect